version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: baha123
      POSTGRES_DB: bahadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend:/app

  web:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.web
    env_file: .env
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/web
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  pgdata: