FROM python:3.11-slim
WORKDIR /app
ENV PIP_DISABLE_PIP_VERSION_CHECK=on POETRY_VIRTUALENVS_CREATE=false \
PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir poetry==1.8.3
COPY backend/pyproject.toml backend/poetry.lock* /app/
RUN poetry install --no-interaction --no-ansi
COPY backend /app
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]